### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by carlosfparada** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#1]
The "fortios.fortianalyzer" collection is not properly documented is doc.ansible.com. It should be populated like the other 2 fortinet collections available at https://docs.ansible.com/ansible/latest/collections/fortinet/. As I was using this collection, I realized the code already contains a good documentation set for all modules, so it should be a matter of generating it and make it available.

**Comment by dux-fortinet** [comment]
You can see the document at https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/ 
Currently, our document is not available at docs.ansible.com

**Comment by dux-fortinet** [comment]
Please check https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/
Thanks.
